#!/usr/bin/env python3
# Copyright (c) 2026 Boon Suan Ho
# SPDX-License-Identifier: MIT

"""Compute the 4AP-free permutation constructed in Boon Suan Ho's paper.

This is a standard-library Python port of the singleton-target construction in
``FourAP/Extension.lean`` and ``FourAP/Construction.lean``. The Lean development
proves the construction correct; this Python implementation is checked against
its finite stages by the repository's tests.

The default permutation has nonnegative values and zero-based positions::

    >>> permutation = Permutation()
    >>> permutation.prefix(11)
    [0, 1, 3, 2, 11, 7, 15, 9, 5, 6, 4]
    >>> permutation.value(4)
    11
    >>> permutation.position(11)
    4

``Permutation(positive=True)`` adds one to every value. Positions remain
zero-based, so its first value is 1 and the position of 1 is 0. Each instance
retains its growing prefix and inverse lookup table, allowing later queries to
reuse earlier work. Neither direction computes stages beyond the first stage
that answers the query.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable, Iterator
from functools import cmp_to_key


def _natural(value: int, name: str) -> int:
    """Validate a public natural-number argument, excluding booleans."""
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an integer, not {type(value).__name__}")
    if value < 0:
        raise ValueError(f"{name} must be nonnegative")
    return value


def _reverse_binary_compare(a: int, b: int) -> int:
    """Compare in reverse ◁ order, as required by Lemma 1's finite listing.

    Inspect bits from the least significant end. Discard equal low bits until
    the first unequal pair; in reverse ◁ order, its 0 comes before its 1.
    This is the parity recursion used in ``FourAP/Binary.lean``.
    """
    if a == b:
        return 0
    while a % 2 == b % 2:
        a //= 2
        b //= 2
    return a % 2 - b % 2


def _extend(prefix: list[int], targets: set[int]) -> list[int]:
    """Apply Lemma 2 to validated inputs; preserve their order and contents."""
    # Lemma 2, base case: an empty prefix or [0] has largest entry zero.
    # Zero comes first in reverse ◁ order, so this listing retains the prefix.
    if max(prefix, default=0) == 0:
        return sorted(set(prefix) | targets, key=cmp_to_key(_reverse_binary_compare))

    # Lemma 2: split the old word into P₀ and P₁, preserving its order in
    # each parity, and rescale 2x+p to x. Their largest entries are smaller.
    even_prefix = [n // 2 for n in prefix if n % 2 == 0]
    odd_prefix = [n // 2 for n in prefix if n % 2 == 1]

    # Extend the even part first, then restore the values of its new suffix E.
    even_targets = {n // 2 for n in targets if n % 2 == 0}
    even_extension = _extend(even_prefix, even_targets)
    new_evens = [2 * n for n in even_extension[len(even_prefix) :]]
    h = max(new_evens, default=0)

    # Force all normalized odd values below h. After rescaling, every odd
    # integer at most 2h is already in the old prefix or in the new suffix O.
    # This is the coverage used in the paper's odd-before-even inequality.
    odd_targets = {n // 2 for n in targets if n % 2 == 1} | set(range(h))
    odd_extension = _extend(odd_prefix, odd_targets)
    new_odds = [2 * n + 1 for n in odd_extension[len(odd_prefix) :]]

    # Lemma 2's construction is Q = P O E: new odd entries precede new evens.
    return prefix + new_odds + new_evens


def extend(prefix: Iterable[int], targets: Iterable[int]) -> list[int]:
    """Return the extension of ``prefix`` prescribed by Lemma 2.

    ``prefix`` must be a *safe word*: a finite list of distinct nonnegative
    integers whose completion by the binary order is 4AP-free. That mathematical
    precondition is established for every word generated by :class:`Permutation`;
    this function checks the entry types and distinctness, but does not attempt
    to decide safety for an arbitrary user-supplied word.

    ``targets`` may be any iterable of nonnegative integers; repetitions have
    no effect. The result begins with the old prefix and contains the targets
    when the safe-word precondition holds. Neither input is mutated, and the
    result is always a new list. This function uses nonnegative values even
    when working alongside a ``Permutation(positive=True)`` instance.
    """
    word = [_natural(n, f"prefix[{i}]") for i, n in enumerate(prefix)]
    if len(set(word)) != len(word):
        raise ValueError("prefix must contain distinct entries")
    target_set = {_natural(n, f"targets[{i}]") for i, n in enumerate(targets)}
    return _extend(word, target_set)


class Permutation:
    """The paper's canonical permutation, with cached forward and inverse maps.

    Stages force the singleton targets {0}, {1}, {2}, ... in that exact order.
    A query advances only until its answer is present. Prefix growth can be
    large, so caching the stages avoids repeating work across related queries.

    Set ``positive=True`` to shift values by one, as in the paper's theorem.
    Positions are always zero-based. Iterating an instance starts at position
    zero and uses the same shared cache as :meth:`value` and :meth:`position`.
    """

    def __init__(self, *, positive: bool = False) -> None:
        if not isinstance(positive, bool):
            raise TypeError("positive must be a bool")
        self._offset = int(positive)
        self._values: list[int] = []
        self._positions: dict[int, int] = {}
        self._next_target = 0

    def _advance(self) -> None:
        """Construct exactly the next singleton-target stage of the paper."""
        old_length = len(self._values)
        extended = _extend(self._values, {self._next_target})

        # Lemma 2 preserves the old prefix, so only the new suffix needs
        # positions assigned. These positions never change at later stages.
        for index in range(old_length, len(extended)):
            self._positions[extended[index]] = index
        self._values = extended
        self._next_target += 1

    def value(self, index: int) -> int:
        """Return the value at a zero-based position.

        The stopping rule is the final remark's prescription: construct stages
        only until the current prefix has length greater than ``index``.
        """
        index = _natural(index, "index")
        while len(self._values) <= index:
            self._advance()
        return self._values[index] + self._offset

    def position(self, value: int) -> int:
        """Return the zero-based position of a value (the inverse permutation).

        Stop when the value first appears, which may happen well before the
        stage explicitly targeting it. For example, 2063 appears at stage 9.
        With ``positive=True``, the argument is a positive, shifted value.
        """
        value = _natural(value, "value")
        if self._offset and value == 0:
            raise ValueError("value must be positive when positive=True")
        unshifted = value - self._offset
        while unshifted not in self._positions:
            self._advance()
        return self._positions[unshifted]

    def prefix(self, length: int) -> list[int]:
        """Return a new list containing the first ``length`` values."""
        length = _natural(length, "length")
        while len(self._values) < length:
            self._advance()
        return [n + self._offset for n in self._values[:length]]

    def __iter__(self) -> Iterator[int]:
        """Yield values from position zero onward, reusing this instance's cache."""
        index = 0
        while True:
            yield self.value(index)
            index += 1


def _cli_natural(text: str) -> int:
    """Parse a nonnegative command-line integer for argparse."""
    try:
        value = int(text)
    except ValueError as error:
        raise argparse.ArgumentTypeError("expected a nonnegative integer") from error
    if value < 0:
        raise argparse.ArgumentTypeError("expected a nonnegative integer")
    return value


def main(argv: list[str] | None = None) -> None:
    """Print a prefix, a value, or an inverse value using the requested convention."""
    parser = argparse.ArgumentParser(
        description="Compute Ho's canonical 4AP-free permutation.",
        epilog="Positions are always zero-based. --positive adds one to values.",
    )
    query = parser.add_mutually_exclusive_group()
    query.add_argument(
        "--count", type=_cli_natural,
        help="print this many initial values (default: 15)",
    )
    query.add_argument(
        "--index", type=_cli_natural,
        help="print the value at this zero-based position",
    )
    query.add_argument(
        "--inverse", type=_cli_natural,
        help="print the zero-based position of this value",
    )
    parser.add_argument(
        "--positive", action="store_true",
        help="use positive values instead of nonnegative values",
    )
    args = parser.parse_args(argv)
    permutation = Permutation(positive=args.positive)

    if args.index is not None:
        print(permutation.value(args.index))
    elif args.inverse is not None:
        if args.positive and args.inverse == 0:
            parser.error("--inverse must be positive when --positive is selected")
        print(permutation.position(args.inverse))
    else:
        print(permutation.prefix(15 if args.count is None else args.count))


if __name__ == "__main__":
    main()
